name: Test calculations
on:
  pull_request:
    branches:
      - main
      - development

jobs:
  calculations-tests-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Use Node.js 14.16.0
        uses: actions/setup-node@v1
        with:
          node-version: 14.16.0

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test.calc
